# Generated by Django 2.2.1 on 2019-06-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190604_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.SmallIntegerField(choices=[(1, 'Store Manager'), (2, 'Delivery Person'), (3, 'Admin')], default=1),
        ),
    ]
