# Generated by Django 2.2.1 on 2019-06-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20190608_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktransaction',
            name='performed_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
